import html,re
def esc(s):return html.escape(str(s),quote=True)
def matching(L,start):
 d=1
 for i in range(start,len(L)):
  s=L[i].strip()
  if re.match(r'^(page|section|button)\s+".*"\s*=>$',s):d+=1
  elif s=='end':
   d-=1
   if d==0:return i
 raise SyntaxError('TPL Web: missing end')
def block(L,a,b):
 r=[];i=a
 while i<b:
  s=L[i].strip()
  if not s or s.startswith('#') or s.startswith('//'):i+=1;continue
  m=re.match(r'^heading\s+"([^"]*)"$',s)
  if m:r.append('<h1>'+esc(m.group(1))+'</h1>');i+=1;continue
  m=re.match(r'^text\s+"([^"]*)"$',s)
  if m:r.append('<p>'+esc(m.group(1))+'</p>');i+=1;continue
  m=re.match(r'^image\s+"([^"]*)"$',s)
  if m:r.append('<img class="tpl-image" src="'+esc(m.group(1))+'">');i+=1;continue
  m=re.match(r'^link\s+"([^"]*)"\s+to\s+"([^"]*)"$',s)
  if m:r.append('<p><a href="'+esc(m.group(2))+'" target="_blank" rel="noopener">'+esc(m.group(1))+'</a></p>');i+=1;continue
  m=re.match(r'^button\s+"([^"]*)"\s*=>$',s)
  if m:
   e=matching(L,i+1);msg=''
   for x in L[i+1:e]:
    z=re.match(r'^show\s+"([^"]*)"$',x.strip())
    if z:msg=z.group(1);break
   r.append('<button class="tpl-button" data-msg="'+esc(msg)+'">'+esc(m.group(1))+'</button>');i=e+1;continue
  m=re.match(r'^section\s+"([^"]*)"\s*=>$',s)
  if m:e=matching(L,i+1);r.append('<section class="tpl-section"><h2>'+esc(m.group(1))+'</h2>'+block(L,i+1,e)+'</section>');i=e+1;continue
  i+=1
 return ''.join(r)
def compile_web(source):
 L=source.splitlines();title='Thanvi Website';body='';i=0
 while i<len(L):
  s=L[i].strip();m=re.match(r'^website\s+"([^"]*)"$',s)
  if m:title=m.group(1);i+=1;continue
  m=re.match(r'^page\s+"([^"]*)"\s*=>$',s)
  if m:e=matching(L,i+1);body+='<section class="tpl-page"><div class="tpl-nav">'+esc(m.group(1))+'</div>'+block(L,i+1,e)+'</section>';i=e+1;continue
  i+=1
 return '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'''+esc(title)+'''</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial;background:linear-gradient(135deg,#667eea,#764ba2);color:#172033}.wrap{max-width:1050px;margin:auto;padding:28px 18px}.hero{text-align:center;color:white;padding:10px 0 25px}.tpl-page{background:#fff;padding:28px;border-radius:18px;margin:18px 0;box-shadow:0 10px 30px #0002}.tpl-nav{color:#667eea;font-weight:bold;border-bottom:1px solid #eee;padding-bottom:12px}h1{font-size:38px}p{font-size:17px;line-height:1.7}.tpl-section{background:#eef3ff;padding:18px;border-radius:14px;margin-top:18px}.tpl-button{background:#667eea;color:#fff;border:0;border-radius:10px;padding:12px 20px;font-weight:bold;cursor:pointer;margin:8px}.tpl-image{max-width:100%;border-radius:14px}.footer{text-align:center;color:#fff;padding:20px}</style></head><body><main class="wrap"><div class="hero"><h1>'''+esc(title)+'''</h1><p>Generated by Thanvi Programming Language v0.4.0</p></div>'''+body+'''<div class="footer">Powered by Thanvi</div></main><script>document.querySelectorAll('.tpl-button').forEach(b=>b.onclick=()=>alert(b.dataset.msg||'Button clicked!'));</script></body></html>'''
